kotlin.code.style=official
org.gradle.caching=true
org.gradle.parallel=true
org.gradle.jvmargs=-Xmx1g -Dfile.encoding=UTF-8

GROUP=com.debugbundle
VERSION_NAME=1.1.0-SNAPSHOT

POM_DESCRIPTION=DebugBundle Kotlin Android SDK for production debugging bundles.

mavenCentralPublishing=true
mavenCentralAutomaticPublishing=true
mavenCentralDeploymentValidation=NONE
signAllPublications=true
